import * as BaseRepository from './BaseRepository.js';

const dataExam = [
    {
        "id": 1,
        "classSession": "Spring 2024",
        "courseCode": "CSE101",
        "courseName": "Introduction to Computer Science",
        "creditNumber": 3,
        "quantity": 50,
        "examType": "Written exam",
        "session": "Morning",
        "time": "8:00 AM - 10:00 AM",
        "date": "2024-04-25",
        "room": "Room A101",
        "examiner1": "Dr. John Smith",
        "examiner2": "Prof. Jane Doe",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 2,
        "creditClass": "12C1",
        "course": "12"
    },
    {
        "id": 2,
        "classSession": "Fall 2023",
        "courseCode": "MAT201",
        "courseName": "Linear Algebra",
        "creditNumber": 4,
        "quantity": 60,
        "examType": "Written exam",
        "session": "Afternoon",
        "time": "2:00 PM - 4:00 PM",
        "date": "2023-12-15",
        "room": "Room B203",
        "examiner1": "Prof. Sarah Johnson",
        "examiner2": "Dr. Robert Miller",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 5,
        "creditClass": "11A2",
        "course": "11"
    },
    {
        "id": 3,
        "classSession": "Spring 2024",
        "courseCode": "BIO101",
        "courseName": "Biology 101",
        "creditNumber": 3,
        "quantity": 45,
        "examType": "Practical exam",
        "session": "Morning",
        "time": "9:00 AM - 11:00 AM",
        "date": "2024-05-10",
        "room": "Room C101",
        "examiner1": "Dr. Emily White",
        "examiner2": "Prof. Michael Green",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 3,
        "creditClass": "12B3",
        "course": "12"
    },
    {
        "id": 4,
        "classSession": "Winter 2023",
        "courseCode": "ENG301",
        "courseName": "Shakespearean Literature",
        "creditNumber": 3,
        "quantity": 30,
        "examType": "Oral exam",
        "session": "Evening",
        "time": "6:00 PM - 8:00 PM",
        "date": "2023-11-20",
        "room": "Room A205",
        "examiner1": "Prof. William Harris",
        "examiner2": "Dr. Elizabeth Brown",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 1,
        "creditClass": "10C1",
        "course": "10"
    },
    {
        "id": 5,
        "classSession": "Summer 2024",
        "courseCode": "CHE201",
        "courseName": "Organic Chemistry",
        "creditNumber": 4,
        "quantity": 55,
        "examType": "Written exam",
        "session": "Morning",
        "time": "8:30 AM - 10:30 AM",
        "date": "2024-07-05",
        "room": "Room D103",
        "examiner1": "Dr. Richard Smith",
        "examiner2": "Prof. Emma Williams",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 4,
        "creditClass": "11D2",
        "course": "11"
    },
    {
        "id": 6,
        "classSession": "Fall 2023",
        "courseCode": "PHY101",
        "courseName": "Physics 101",
        "creditNumber": 3,
        "quantity": 40,
        "examType": "Written exam",
        "session": "Afternoon",
        "time": "1:00 PM - 3:00 PM",
        "date": "2023-11-30",
        "room": "Room E201",
        "examiner1": "Prof. Jason Brown",
        "examiner2": "Dr. Amy Johnson",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 4,
        "creditClass": "10A3",
        "course": "10"
    },
    {
        "id": 7,
        "classSession": "Spring 2024",
        "courseCode": "ART101",
        "courseName": "Introduction to Art History",
        "creditNumber": 3,
        "quantity": 35,
        "examType": "Written exam",
        "session": "Morning",
        "time": "10:00 AM - 12:00 PM",
        "date": "2024-04-30",
        "room": "Room F105",
        "examiner1": "Prof. Samantha Taylor",
        "examiner2": "Dr. Kevin Jackson",
        "proctor1": "",
        "proctor2": "",
        "dateOfWeek": 1,
        "creditClass": "12A2",
        "course": "12"
    }
];

BaseRepository.setData(dataExam);