import * as BaseRepository from './BaseRepository.js';

const dataExam = [
    {
        "TT": 1,
        "Lớp HP": "ABC123",
        "Mã HP": "CSE101",
        "Tên học phần": "Lập trình cơ bản",
        "Số TC": 3,
        "SL": 50,
        "HT Thi": "Thi viết",
        "Buổi": "Sáng",
        "Giờ thi": "8:00 - 10:00",
        "Ngày thi": "25/04/2024",
        "Phòng thi": "Phòng A101",
        "GV chấm thi 1": "Nguyễn Văn A",
        "GV chấm thi 2": "Nguyễn Văn B",
        "CT 1": "",
        "CT 2": "",
        "Thứ": 2,
        "Lớp": "12C1",
        "Khóa": 12
    },
    {
        "TT": 2,
        "Lớp HP": "DEF456",
        "Mã HP": "MTH202",
        "Tên học phần": "Toán cao cấp",
        "Số TC": 4,
        "SL": 40,
        "HT Thi": "Thi trắc nghiệm",
        "Buổi": "Chiều",
        "Giờ thi": "14:00 - 16:00",
        "Ngày thi": "26/04/2024",
        "Phòng thi": "Phòng B202",
        "GV chấm thi 1": "Phạm Thị C",
        "GV chấm thi 2": "Nguyễn Văn D",
        "CT 1": "",
        "CT 2": "",
        "Thứ": 3,
        "Lớp": "12C2",
        "Khóa": 12
    },
    {
        "TT": 3,
        "Lớp HP": "GHI789",
        "Mã HP": "ENG101",
        "Tên học phần": "Tiếng Anh cơ bản",
        "Số TC": 2,
        "SL": 30,
        "HT Thi": "Thi lý thuyết",
        "Buổi": "Sáng",
        "Giờ thi": "9:00 - 11:00",
        "Ngày thi": "27/04/2024",
        "Phòng thi": "Phòng C303",
        "GV chấm thi 1": "Lê Thị E",
        "GV chấm thi 2": "Trần Văn F",
        "CT 1": "",
        "CT 2": "",
        "Thứ": 4,
        "Lớp": "12C3",
        "Khóa": 12
    },
    {
        "TT": 4,
        "Lớp HP": "XYZ789",
        "Mã HP": "PHY303",
        "Tên học phần": "Vật lý cơ bản",
        "Số TC": 3,
        "SL": 45,
        "HT Thi": "Thi thực hành",
        "Buổi": "Chiều",
        "Giờ thi": "13:00 - 15:00",
        "Ngày thi": "28/04/2024",
        "Phòng thi": "Phòng D404",
        "GV chấm thi 1": "Hoàng Văn G",
        "GV chấm thi 2": "Nguyễn Thị H",
        "CT 1": "",
        "CT 2": "",
        "Thứ": 5,
        "Lớp": "12C4",
        "Khóa": 12
    },
    {
        "TT": 5,
        "Lớp HP": "JKL321",
        "Mã HP": "BIO202",
        "Tên học phần": "Sinh học cơ bản",
        "Số TC": 3,
        "SL": 40,
        "HT Thi": "Thi thực hành",
        "Buổi": "Sáng",
        "Giờ thi": "10:00 - 12:00",
        "Ngày thi": "29/04/2024",
        "Phòng thi": "Phòng E505",
        "GV chấm thi 1": "Trần Văn I",
        "GV chấm thi 2": "Lê Thị K",
        "CT 1": "",
        "CT 2": "",
        "Thứ": 6,
        "Lớp": "12C5",
        "Khóa": 12
    }
];

BaseRepository.setData(dataExam);